# Generated by Django 2.1.7 on 2019-03-02 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_auto_20190226_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='books',
            field=models.ManyToManyField(to='biblioteca.Book'),
        ),
    ]
