# Generated by Django 2.1.7 on 2019-03-04 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0003_store_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='university_type',
            field=models.CharField(choices=[('PUBLIC', 'A public university'), ('PRIVATE', 'A private university')], default=(('PUBLIC', 'A public university'), ('PRIVATE', 'A private university')), max_length=100),
        ),
    ]
