# Generated by Django 2.1.7 on 2019-03-04 23:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0004_university_university_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('first_name', models.CharField(help_text='Nombre verdadero', max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='last name')),
                ('marital_status', models.CharField(choices=[('Single', 'Single'), ('Merried', 'Merried'), ('Divorced', 'Divorced'), ('Separated', 'Separated'), ('Widow', 'Widow'), ('Widower', 'Widower')], default=(('Single', 'Single'), ('Merried', 'Merried'), ('Divorced', 'Divorced'), ('Separated', 'Separated'), ('Widow', 'Widow'), ('Widower', 'Widower')), max_length=6)),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], default=(('Female', 'Female'), ('Male', 'Male')), max_length=2)),
                ('address', models.CharField(max_length=200)),
                ('telephone_number', models.CharField(max_length=12)),
                ('additional_data', models.TextField(blank=True, max_length=500)),
                ('birthday', models.DateField()),
            ],
            options={
                'verbose_name': 'student',
                'verbose_name_plural': 'students',
            },
        ),
        migrations.AlterField(
            model_name='university',
            name='university_type',
            field=models.CharField(choices=[('Public', 'A public university'), ('Private', 'A private university')], default=(('Public', 'A public university'), ('Private', 'A private university')), max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='university', to='biblioteca.University'),
        ),
    ]
