# Generated by Django 2.1.7 on 2019-03-04 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0006_auto_20190304_2328'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='university',
            options={'ordering': ['full_name'], 'verbose_name': 'university', 'verbose_name_plural': 'universities'},
        ),
        migrations.AlterField(
            model_name='university',
            name='university_type',
            field=models.CharField(choices=[('Public', 'A public university'), ('Private', 'A private university')], default=(('Public', 'A public university'), ('Private', 'A private university')), max_length=100),
        ),
        migrations.AddIndex(
            model_name='university',
            index=models.Index(fields=['full_name'], name='biblioteca__full_na_e09ffa_idx'),
        ),
    ]
