# Generated by Django 2.1.7 on 2019-03-04 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0007_auto_20190304_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='marital_status',
            field=models.CharField(choices=[('Single', 'Single'), ('Merried', 'Merried'), ('Divorced', 'Divorced'), ('Separated', 'Separated'), ('Widow', 'Widow'), ('Widower', 'Widower')], default=(('Single', 'Single'), ('Merried', 'Merried'), ('Divorced', 'Divorced'), ('Separated', 'Separated'), ('Widow', 'Widow'), ('Widower', 'Widower')), max_length=10),
        ),
        migrations.AlterField(
            model_name='university',
            name='university_type',
            field=models.CharField(choices=[('Public', 'A public university'), ('Private', 'A private university')], default=(('Public', 'A public university'), ('Private', 'A private university')), max_length=100),
        ),
    ]
