# Generated by Django 2.1.7 on 2019-03-14 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0022_auto_20190313_2136'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contacto',
        ),
        migrations.AlterField(
            model_name='university',
            name='university_type',
            field=models.CharField(choices=[('Public', 'A public university'), ('Private', 'A private university')], default=(('Public', 'A public university'), ('Private', 'A private university')), max_length=100),
        ),
    ]
